# Generated by Django 5.2.3 on 2025-07-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('contactno', models.CharField(default='', max_length=19)),
            ],
        ),
    ]
