# Generated by Django 5.2.3 on 2025-07-20 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(default=' ', max_length=100)),
                ('comment', models.CharField(default=' ', max_length=500)),
                ('contactno', models.CharField(default=' ', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('emailorder', models.CharField(default=' ', max_length=100)),
                ('name2', models.CharField(default=' ', max_length=100)),
                ('phonenumber', models.CharField(default=' ', max_length=15)),
                ('address', models.CharField(default=' ', max_length=500)),
                ('address2', models.CharField(default=' ', max_length=500)),
                ('famousplace', models.CharField(default=' ', max_length=300)),
                ('state', models.CharField(default=' ', max_length=30)),
                ('city', models.CharField(default=' ', max_length=30)),
                ('zip', models.CharField(default=' ', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='orderupdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0)),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_desc', models.CharField(max_length=1200)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('pro_date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
